name: Tests

on:
  pull_request:
    branches: [ production ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          BASE_URL: 'https://ada-dev.hemmer.dev'

      - name: Archive Cypress videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos